Repository ViaQ/logging-fluentd, pull requests merged in 2022-03, with the labels that each got.

#6 LOG-1772: Update lib Gemfile.lock and other 1.7.4 refs
  .gitignore
  Dockerfile.unit
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  fluentd/lib/filter_elasticsearch_genid_ext/Gemfile.lock
  fluentd/lib/filter_parse_json_field/Gemfile.lock
  fluentd/lib/filter_parse_json_field/filter_parse_json_field.gemspec
  fluentd/lib/fluent-plugin-collected/Gemfile.lock
  fluentd/lib/fluent-plugin-remote_syslog/Gemfile.lock
  fluentd/lib/fluent-plugin-viaq_data_model/Gemfile.lock
  fluentd/lib/formatter-single-json-value/Gemfile.lock
  fluentd/lib/parser_viaq_host_audit/Gemfile.lock
  fluentd/lib/remote_syslog_sender/Gemfile.lock
  fluentd/lib/syslog_protocol/Gemfile.lock
Labels: approved, lgtm

#9 LOG-2289: Update fluent-plugin-kubernetes_metadata to fix the test ap…
  Makefile
  fluentd/Gemfile
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/aws-eventstream/aws-eventstream.gemspec
  fluentd/vendored_gem_src/aws-partitions/aws-partitions.gemspec
  fluentd/vendored_gem_src/aws-sdk-cloudwatchlogs/aws-sdk-cloudwatchlogs.gemspec
  fluentd/vendored_gem_src/aws-sdk-core/aws-sdk-core.gemspec
  fluentd/vendored_gem_src/aws-sigv4/aws-sigv4.gemspec
  fluentd/vendored_gem_src/concurrent-ruby/concurrent-ruby.gemspec
  fluentd/vendored_gem_src/faraday/faraday.gemspec
  fluentd/vendored_gem_src/fluent-plugin-grafana-loki/fluent-plugin-grafana-loki.gemspec
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/Gemfile.lock
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/README.md
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/fluent-plugin-kubernetes_metadata_filter.gemspec
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/lib/fluent/plugin/filter_kubernetes_metadata.rb
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/lib/fluent/plugin/kubernetes_metadata_test_api_adapter.rb
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/release_notes.md
  fluentd/vendored_gem_src/fluent-plugin-systemd/fluent-plugin-systemd.gemspec
  fluentd/vendored_gem_src/jmespath/jmespath.gemspec
  fluentd/vendored_gem_src/mime-types-data/History.md
  fluentd/vendored_gem_src/mime-types-data/data/content_type_mime.db
  fluentd/vendored_gem_src/mime-types-data/data/ext_mime.db
  fluentd/vendored_gem_src/mime-types-data/data/mime-types.json
  fluentd/vendored_gem_src/mime-types-data/data/mime.content_type.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.docs.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.encoding.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.flags.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.friendly.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.pext.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.use_instead.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.xrefs.column
  fluentd/vendored_gem_src/mime-types-data/lib/mime/types/data.rb
  fluentd/vendored_gem_src/mime-types-data/mime-types-data.gemspec
  fluentd/vendored_gem_src/mime-types-data/types/application.yaml
  fluentd/vendored_gem_src/mime-types-data/types/image.yaml
  fluentd/vendored_gem_src/mime-types-data/types/message.yaml
  fluentd/vendored_gem_src/mime-types-data/types/provisional-standard-types.yaml
  fluentd/vendored_gem_src/mime-types-data/types/text.yaml
  fluentd/vendored_gem_src/mime-types/mime-types.gemspec
  fluentd/vendored_gem_src/multi_json/multi_json.gemspec
  fluentd/vendored_gem_src/net-http-persistent/net-http-persistent.gemspec
  fluentd/vendored_gem_src/netrc/netrc.gemspec
  fluentd/vendored_gem_src/oj/oj.gemspec
  fluentd/vendored_gem_src/prometheus-client/prometheus-client.gemspec
  fluentd/vendored_gem_src/quantile/quantile.gemspec
  fluentd/vendored_gem_src/tzinfo-data/tzinfo-data.gemspec
  fluentd/vendored_gem_src/tzinfo/tzinfo.gemspec
  fluentd/vendored_gem_src/uuidtools/uuidtools.gemspec
Labels: approved, lgtm

#14 LOG-2266: fix parsing of audit logs to not depend upon position
  fluentd/lib/parser_viaq_host_audit/lib/viaq_host_audit.rb
  fluentd/lib/parser_viaq_host_audit/test/parser_viaq_host_audit_test.rb
Labels: approved, lgtm

#8 LOG-2099: Add sequence number to log messages to fix entry order
  .gitignore
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_openshift.rb
  fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_openshift.rb
Labels: approved, lgtm

#17 LOG-2291: Add sequence number to log messages to fix entry order
  .gitignore
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_openshift.rb
  fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_openshift.rb
Labels: approved, lgtm

#11 Enabled passing umask on the command line (LOG-2176)
  fluentd/fluent.source0001.patch
Labels: approved, lgtm

#18 LOG-2353: Update base images to be public
  fluentd/Dockerfile
  fluentd/origin-meta.yaml
Labels: approved, lgtm

#19 LOG-2176: corrections to the previous commit
  fluentd/Dockerfile
  fluentd/Dockerfile.in
  fluentd/fluentd.source0001.patch
Labels: approved, lgtm

#12 Update fluent-plugin-kubernetes_metadata to fix the testapiadapter
  .gitignore
  fluentd/Gemfile
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/aws-eventstream/aws-eventstream.gemspec
  fluentd/vendored_gem_src/aws-partitions/aws-partitions.gemspec
  fluentd/vendored_gem_src/aws-sdk-cloudwatchlogs/aws-sdk-cloudwatchlogs.gemspec
  fluentd/vendored_gem_src/aws-sdk-core/aws-sdk-core.gemspec
  fluentd/vendored_gem_src/aws-sigv4/aws-sigv4.gemspec
  fluentd/vendored_gem_src/concurrent-ruby/concurrent-ruby.gemspec
  fluentd/vendored_gem_src/faraday/faraday.gemspec
  fluentd/vendored_gem_src/fluent-plugin-grafana-loki/fluent-plugin-grafana-loki.gemspec
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/Gemfile.lock
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/README.md
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/fluent-plugin-kubernetes_metadata_filter.gemspec
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/lib/fluent/plugin/filter_kubernetes_metadata.rb
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/lib/fluent/plugin/kubernetes_metadata_test_api_adapter.rb
  fluentd/vendored_gem_src/fluent-plugin-kubernetes_metadata_filter/release_notes.md
  fluentd/vendored_gem_src/fluent-plugin-systemd/fluent-plugin-systemd.gemspec
  fluentd/vendored_gem_src/jmespath/jmespath.gemspec
  fluentd/vendored_gem_src/mime-types-data/History.md
  fluentd/vendored_gem_src/mime-types-data/data/content_type_mime.db
  fluentd/vendored_gem_src/mime-types-data/data/ext_mime.db
  fluentd/vendored_gem_src/mime-types-data/data/mime-types.json
  fluentd/vendored_gem_src/mime-types-data/data/mime.content_type.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.docs.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.encoding.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.flags.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.friendly.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.pext.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.use_instead.column
  fluentd/vendored_gem_src/mime-types-data/data/mime.xrefs.column
  fluentd/vendored_gem_src/mime-types-data/lib/mime/types/data.rb
  fluentd/vendored_gem_src/mime-types-data/mime-types-data.gemspec
  fluentd/vendored_gem_src/mime-types-data/types/application.yaml
  fluentd/vendored_gem_src/mime-types-data/types/image.yaml
  fluentd/vendored_gem_src/mime-types-data/types/message.yaml
  fluentd/vendored_gem_src/mime-types-data/types/provisional-standard-types.yaml
  fluentd/vendored_gem_src/mime-types-data/types/text.yaml
  fluentd/vendored_gem_src/mime-types/mime-types.gemspec
  fluentd/vendored_gem_src/multi_json/multi_json.gemspec
  fluentd/vendored_gem_src/net-http-persistent/net-http-persistent.gemspec
  fluentd/vendored_gem_src/netrc/netrc.gemspec
  fluentd/vendored_gem_src/oj/oj.gemspec
  fluentd/vendored_gem_src/prometheus-client/prometheus-client.gemspec
  fluentd/vendored_gem_src/quantile/quantile.gemspec
  fluentd/vendored_gem_src/tzinfo-data/tzinfo-data.gemspec
  fluentd/vendored_gem_src/tzinfo/tzinfo.gemspec
  fluentd/vendored_gem_src/uuidtools/uuidtools.gemspec
Labels: approved, lgtm

#5 sync midstream back to upstream
  fluentd/Dockerfile
  fluentd/Dockerfile.in
Labels: approved, release/v1.7.4

#20 LOG-2291: Fix plugin to add sequence number
  fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
  fluentd/lib/fluent-plugin-viaq_data_model/test/test_filter_viaq_data_model.rb
Labels: approved, release/v1.14.5

#21 LOG-2220: Fluentd collector not setting labels from /var/log/pods paths
  fluentd/lib/fluent-plugin-collected/lib/fluent/plugin/in_collected_tail_monitor.rb
  fluentd/lib/fluent-plugin-collected/test/plugin/test_in_collected_tail_monitor.rb
Labels: approved, lgtm
