Repository ViaQ/logging-fluentd, pull requests merged in 2023-11, with the labels that each got.

#105 LOG-4281: Fluentd is unable to forward logs to external ipv6 elasticsearch instance
  fluentd/fluent-plugin-elasticsearch.source0001.patch
Labels: approved, lgtm, jira/valid-reference, release/5.7

#106 LOG-4811: Fluentd is unable to forward logs to external ipv6 elasticsearch instance
  fluentd/Dockerfile
  fluentd/fluent-plugin-elasticsearch.source0001.patch
Labels: approved, lgtm, jira/valid-reference, release/5.8, release/5.9

#100 LOG-4366: fix ruby net/http.rb to honor no_proxy in start method
  fluentd/Dockerfile
  fluentd/log4366_ruby_lib_net_http.patch
Labels: approved, lgtm, jira/valid-reference, release/5.8
