Repository ViaQ/logging-fluentd, pull requests merged in 2023-05, with the labels that each got.

#61 LOG-3815: Update rack to address fix CVE-2023-27539
  fluentd/Gemfile.lock
Labels: approved, lgtm, jira/valid-reference, release/5.8

#62 LOG-3816: Update activesupport and activemodel gems to address fix CVE-2023-28120
  fluentd/Gemfile.lock
Labels: approved, lgtm, jira/valid-reference, release/5.8

#83 LOG-3633: fix fluentd position file closing watches on re-used inodes
  fluentd/fluentd.source0001.patch
Labels: approved, lgtm, jira/valid-reference, release/5.6

#78 [release-5.7]LOG-3815: Update rack to address fix CVE-2023-27539
  fluentd/Gemfile.lock
  fluentd/rh-manifest.txt
  fluentd/vendored_gem_src/rack/CHANGELOG.md
  fluentd/vendored_gem_src/rack/lib/rack.rb
  fluentd/vendored_gem_src/rack/lib/rack/constants.rb
  fluentd/vendored_gem_src/rack/lib/rack/multipart.rb
  fluentd/vendored_gem_src/rack/lib/rack/query_parser.rb
  fluentd/vendored_gem_src/rack/lib/rack/request.rb
  fluentd/vendored_gem_src/rack/lib/rack/version.rb
  fluentd/vendored_gem_src/rack/rack.gemspec
Labels: approved, lgtm, jira/valid-reference, release/5.7

#85 Update owners file
  OWNERS
Labels: approved, lgtm

#88 [ruby31-v1.14.x] LOG-3314:Upgrade fluent-plugin-kafka to 0.19.0
  fluentd/Gemfile
  fluentd/Gemfile.lock
Labels: approved, lgtm, jira/valid-reference, release/5.8

#89 LOG-4151: add patch for: Fluentd fix missing nil check for rotated_tw in update_watcher
  fluentd/fluentd.source0001.patch
Labels: approved, lgtm, jira/valid-reference, release/5.7

#90 LOG-4150: add patch for: Fluentd fix missing nil check for rotated_tw in update_watcher
  fluentd/Dockerfile
  fluentd/fluentd.source0001.patch
Labels: approved, lgtm, jira/valid-reference, release/5.8

#86 [release-5.7] Update owners file
  OWNERS
Labels: approved, lgtm

#91 LOG-4149: fix fluentd position file closing watches on re-used inodes
  fluentd/fluentd.source0001.patch
Labels: approved, lgtm, release/5.7
